import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";
import { MethodButton } from "../components/MethodButton";

const Gestionaire: React.FC = () => {
  return (
    <div id="page-gestionaire-6">
    <div id="iufw7o" style={{"display": "flex", "height": "100vh", "fontFamily": "Arial, sans-serif", "--chart-color-palette": "default"}}>
      <nav id="icgilg" style={{"width": "250px", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "padding": "20px", "overflowY": "auto", "display": "flex", "flexDirection": "column", "--chart-color-palette": "default"}}>
        <h2 id="i1a11k" style={{"marginTop": "0", "fontSize": "24px", "marginBottom": "30px", "fontWeight": "bold", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="ihe6m3" style={{"display": "flex", "flexDirection": "column", "flex": "1", "--chart-color-palette": "default"}}>
          <a id="i897il" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/centre_de_congres">{"Centre_de_congres"}</a>
          <a id="iehq27" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/element                                                        ">{"Element"}</a>
          <a id="itaomh" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/evenement">{"Evenement"}</a>
          <a id="i5g9kd" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/option">{"option"}</a>
          <a id="iroy8o" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/materiel">{"materiel"}</a>
          <a id="iq5tvn" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/prestation">{"prestation"}</a>
          <a id="iqopcr" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "rgba(255,255,255,0.2)", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/gestionaire">{"gestionaire"}</a>
          <a id="i5f77p" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/reservation">{"Reservation"}</a>
          <a id="ir2aal" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/indisponiblite">{"Indisponiblite"}</a>
        </div>
        <p id="is32hx" style={{"marginTop": "auto", "paddingTop": "20px", "borderTop": "1px solid rgba(255,255,255,0.2)", "fontSize": "11px", "opacity": "0.8", "textAlign": "center", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="i6aafd" style={{"flex": "1", "padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
        <h1 id="ifik6j" style={{"marginTop": "0", "color": "#333", "fontSize": "32px", "marginBottom": "10px", "--chart-color-palette": "default"}}>{"gestionaire"}</h1>
        <p id="ini3pj" style={{"color": "#666", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"Manage gestionaire data"}</p>
        <TableBlock id="table-gestionaire-6" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="gestionaire List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Liste Congres", "column_type": "field", "field": "liste_congres", "type": "any", "required": true}, {"label": "Date Du Jour", "column_type": "field", "field": "date_du_jour", "type": "date", "required": true}, {"label": "Liste Diponiblité", "column_type": "field", "field": "liste_diponiblité", "type": "any", "required": true}, {"label": "Liste DispoibilitéS PasséEs", "column_type": "field", "field": "liste_dispoibilités_passées", "type": "any", "required": true}, {"label": "Reserver", "column_type": "lookup", "path": "reserver", "entity": "Centre_de_congres", "field": "nomC", "type": "list", "required": false}, {"label": "Effectuer", "column_type": "lookup", "path": "effectuer", "entity": "Reservation", "field": "nom", "type": "list", "required": false}], "formColumns": [{"column_type": "field", "field": "liste_congres", "label": "liste_congres", "type": "any", "required": true, "defaultValue": null}, {"column_type": "field", "field": "date_du_jour", "label": "date_du_jour", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "liste_diponiblité", "label": "liste_diponiblité", "type": "any", "required": true, "defaultValue": null}, {"column_type": "field", "field": "liste_dispoibilités_passées", "label": "liste_dispoibilités_passées", "type": "any", "required": true, "defaultValue": null}, {"column_type": "lookup", "path": "effectuer", "field": "effectuer", "lookup_field": "nom", "entity": "Reservation", "type": "list", "required": false}, {"column_type": "lookup", "path": "reserver", "field": "reserver", "lookup_field": "nomC", "entity": "Centre_de_congres", "type": "list", "required": false}]}} dataBinding={{"entity": "gestionaire", "endpoint": "/gestionaire/"}} />
        <div id="ibz2k8" style={{"marginTop": "20px", "display": "flex", "gap": "10px", "flexWrap": "wrap", "--chart-color-palette": "default"}}>
          <MethodButton id="ie7q6p" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/gestionaire/{gestionaire_id}/methods/verifieDisponibilite/" label="+ verifieDisponibilite" isInstanceMethod={true} instanceSourceTableId="table-gestionaire-6" />
          <MethodButton id="id70hg" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/gestionaire/{gestionaire_id}/methods/creerReservation/" label="+ creerReservation" isInstanceMethod={true} instanceSourceTableId="table-gestionaire-6" />
          <MethodButton id="ihe34a" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/gestionaire/{gestionaire_id}/methods/ajouterOptions/" label="+ ajouterOptions" isInstanceMethod={true} instanceSourceTableId="table-gestionaire-6" />
        </div>
      </main>
    </div>    </div>
  );
};

export default Gestionaire;
