import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";
import { MethodButton } from "../components/MethodButton";

const Reservation: React.FC = () => {
  return (
    <div id="page-reservation-7">
    <div id="ioepkr" style={{"display": "flex", "height": "100vh", "fontFamily": "Arial, sans-serif", "--chart-color-palette": "default"}}>
      <nav id="i2x1se" style={{"width": "250px", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "padding": "20px", "overflowY": "auto", "display": "flex", "flexDirection": "column", "--chart-color-palette": "default"}}>
        <h2 id="i9bd4w" style={{"marginTop": "0", "fontSize": "24px", "marginBottom": "30px", "fontWeight": "bold", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="ido81h" style={{"display": "flex", "flexDirection": "column", "flex": "1", "--chart-color-palette": "default"}}>
          <a id="imcips" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/centre_de_congres">{"Centre_de_congres"}</a>
          <a id="ic4xj4" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/element                                                        ">{"Element"}</a>
          <a id="iwcktb" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/evenement">{"Evenement"}</a>
          <a id="i3ggjz" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/option">{"option"}</a>
          <a id="izyqbs" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/materiel">{"materiel"}</a>
          <a id="iu6qg5" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/prestation">{"prestation"}</a>
          <a id="iqcf8s" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/gestionaire">{"gestionaire"}</a>
          <a id="ir1pk9" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "rgba(255,255,255,0.2)", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/reservation">{"Reservation"}</a>
          <a id="i9m9lg" style={{"color": "white", "textDecoration": "none", "padding": "10px 15px", "display": "block", "background": "transparent", "borderRadius": "4px", "marginBottom": "5px", "--chart-color-palette": "default"}} href="/indisponiblite">{"Indisponiblite"}</a>
        </div>
        <p id="iml0jg" style={{"marginTop": "auto", "paddingTop": "20px", "borderTop": "1px solid rgba(255,255,255,0.2)", "fontSize": "11px", "opacity": "0.8", "textAlign": "center", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="iqgg5j" style={{"flex": "1", "padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default"}}>
        <h1 id="iwxdwn" style={{"marginTop": "0", "color": "#333", "fontSize": "32px", "marginBottom": "10px", "--chart-color-palette": "default"}}>{"Reservation"}</h1>
        <p id="io9jhs" style={{"color": "#666", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"Manage Reservation data"}</p>
        <TableBlock id="table-reservation-7" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="Reservation List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Nom", "column_type": "field", "field": "nom", "type": "str", "required": true}, {"label": "Liste Option", "column_type": "field", "field": "liste_option", "type": "any", "required": true}, {"label": "Status", "column_type": "field", "field": "Status", "type": "enum", "options": ["Anuler", "Confirmer", "En_attente"], "required": true}, {"label": "Date DebutR", "column_type": "field", "field": "date_debutR", "type": "date", "required": true}, {"label": "Date FinR", "column_type": "field", "field": "date_finR", "type": "date", "required": true}, {"label": "Lier", "column_type": "lookup", "path": "lier", "entity": "Evenement", "field": "nomEve", "type": "list", "required": true}, {"label": "Etre Effectuer", "column_type": "lookup", "path": "etre_effectuer", "entity": "gestionaire", "field": "liste_congres", "type": "any", "required": true}, {"label": "Peut Inclure", "column_type": "lookup", "path": "peut_inclure", "entity": "option", "field": "nomO", "type": "list", "required": false}], "formColumns": [{"column_type": "field", "field": "nom", "label": "nom", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "liste_option", "label": "liste_option", "type": "any", "required": true, "defaultValue": null}, {"column_type": "field", "field": "Status", "label": "Status", "type": "enum", "required": true, "defaultValue": null, "options": ["Anuler", "Confirmer", "En_attente"]}, {"column_type": "field", "field": "date_debutR", "label": "date_debutR", "type": "date", "required": true, "defaultValue": null}, {"column_type": "field", "field": "date_finR", "label": "date_finR", "type": "date", "required": true, "defaultValue": null}, {"column_type": "lookup", "path": "etre_effectuer", "field": "etre_effectuer", "lookup_field": "liste_congres", "entity": "gestionaire", "type": "str", "required": true}, {"column_type": "lookup", "path": "peut_inclure", "field": "peut_inclure", "lookup_field": "nomO", "entity": "option", "type": "list", "required": false}, {"column_type": "lookup", "path": "indisponiblite", "field": "indisponiblite", "lookup_field": "date_debut", "entity": "Indisponiblite", "type": "str", "required": true}, {"column_type": "lookup", "path": "lier", "field": "lier", "lookup_field": "nomEve", "entity": "Evenement", "type": "list", "required": true}]}} dataBinding={{"entity": "Reservation", "endpoint": "/reservation/"}} />
        <div id="ii8z12" style={{"marginTop": "20px", "display": "flex", "gap": "10px", "flexWrap": "wrap", "--chart-color-palette": "default"}}>
          <MethodButton id="i6bixp" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/reservation/{reservation_id}/methods/confirmer/" label="+ confirmer" isInstanceMethod={true} instanceSourceTableId="table-reservation-7" />
          <MethodButton id="idyvt4" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/reservation/{reservation_id}/methods/calculerprix/" label="+ calculerprix" isInstanceMethod={true} instanceSourceTableId="table-reservation-7" />
          <MethodButton id="ig2gl2" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/reservation/{reservation_id}/methods/annuler/" label="+ annuler" isInstanceMethod={true} instanceSourceTableId="table-reservation-7" />
          <MethodButton id="iej2of" className="action-button-component" style={{"display": "inline-flex", "alignItems": "center", "padding": "6px 14px", "background": "linear-gradient(90deg, #2563eb 0%, #1e40af 100%)", "color": "#fff", "textDecoration": "none", "borderRadius": "4px", "fontSize": "13px", "fontWeight": "600", "letterSpacing": "0.01em", "cursor": "pointer", "border": "none", "boxShadow": "0 1px 4px rgba(37,99,235,0.10)", "transition": "background 0.2s", "--chart-color-palette": "default"}} endpoint="/reservation/{reservation_id}/methods/inclureOption/" label="+ inclureOption" isInstanceMethod={true} instanceSourceTableId="table-reservation-7" />
        </div>
      </main>
    </div>    </div>
  );
};

export default Reservation;
